service: evacuaid-backendPython

provider:
  name: aws
  runtime: python3.7
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:UpdateTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:*
      Resource:
        - { "Fn::ImportValue": evacuaid-backend-dev-table }
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource:
        - {
            "Fn::Join":
              [
                "/",
                [
                  { "Fn::ImportValue": evacuaid-backend-dev-table },
                  "index",
                  "*",
                ],
              ],
          }

functions:
  fire-data-cron:
    description: Cron which gets the fire data
    handler: fireCron.eventCreater
    events:
      - schedule: rate(1 minute)
    timeout: 900
  get-data:
    handler: fireCron.getFires
    events:
      - http:
          method: GET
          path: getFires
          cors: true
